### ISSUE TITLE
Missing Datasource LocalInflux in Grafana Dashboard

### ISSUE THREAD

**Issue by JenSeReal** [inspectIT/inspectit-ocelot-demo#22]
When try to execute [docker-compose-influxdb-jaeger.yml](https://github.com/inspectIT/inspectit-ocelot-demo/blob/main/docker-compose-influxdb-jaeger.yml) or [docker-compose-influxdb-zipkin.yml](https://github.com/inspectIT/inspectit-ocelot-demo/blob/main/docker-compose-influxdb-zipkin.yml) and open Grafana and try to open a dashboard you are greeted with a error message from Grafana, stating that the datasource LocalInflux could not be found. 
![Screenshot 2023-01-16 160000](https://user-images.githubusercontent.com/33718194/212710590-4c8e17a1-d0d1-4ec8-8dc7-8a0cd42300fb.png)
Then navigate to the datasources tab and one can see that it is indeed missing.
![Screenshot 2023-01-16 160049](https://user-images.githubusercontent.com/33718194/212710637-460a522b-628e-45b8-8a88-bce17ba1c816.png)
I tried adding the datasource again by hand and named it LocalInflux 

![Screenshot 2023-01-16 160145](https://user-images.githubusercontent.com/33718194/212711351-080947ae-6004-495a-98d2-ab7fea92f368.png)
![Screenshot 2023-01-16 160200](https://user-images.githubusercontent.com/33718194/212711370-5b00195c-d1d5-46fd-a0f7-48242c43b655.png)

After that I got some data back.
![Screenshot 2023-01-16 160351](https://user-images.githubusercontent.com/33718194/212711497-6f89d69e-3f54-4714-8f19-6dd3e58a9ca0.png)

So InfluxDB is up and running, but Grafana is not able to add the datasource defined in the [Grafana Folder](https://github.com/inspectIT/inspectit-ocelot-demo/tree/main/grafana) folder.

**Comment by tobiangerstein** [comment]
Thx for pointing to this issue :) fun fact @danipaniii  just discovered this issue as well. @JenSeReal  do you want to take care? Otherwise @danipaniii  can also fix it with his next pull request ;)
